<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * adresseCabinetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adresseCabinetRepository extends \Doctrine\ORM\EntityRepository
{

    function ExistanceAdresse($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("
    select s from SanteSpecialisteBundle:adresseCabinet s
    WHERE s.id LIKE :id")
            ->setParameter('id','%'.$id.'%');
        $q=$query->getResult();
        if ($q == null)
        {return 1;}
        else return $q ;
    }
}
