<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * horaireTravailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class horaireTravailRepository extends \Doctrine\ORM\EntityRepository
{
    function FindIdHoraire($id,$jour)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s FETCH FIRST from SanteSpecialisteBundle:horaireTravail s 
    WHERE s.id LIKE :id and s.joursemaine LIKE :jour 
      ")
            ->setParameter('id', '%' . $id . '%')->setParameter('jour', '%' . $jour . '%');
       return $query->getResult();

    }
}
