<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * justificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class justificationRepository extends \Doctrine\ORM\EntityRepository
{
}
