<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * MedecinSpecialisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedecinSpecialisteRepository extends \Doctrine\ORM\EntityRepository
{
    function findmedecin($nom,$prenom,$specialite,$adresse)
    {
        $etat=1;
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from SanteSpecialisteBundle:MedecinSpecialiste s 
    WHERE s.nom LIKE :nom AND s.prenom LIKE :prenom AND s.specialite LIKE :specialite AND s.gouvernorat LIKE :adresse AND s.etatverif LIKE :etat
    ORDER BY s.rating DESC 
      ")
            ->setParameter('nom', '%' . $nom . '%')->setParameter('etat', '%' . $etat . '%')->setParameter('prenom', '%' . $prenom . '%')->setParameter('specialite', '%' . $specialite . '%')->setParameter('adresse', '%' . $adresse . '%');
        return $query->getResult();
    }
    function findmedecinverif2($nom,$prenom,$specialite,$cin)
    {
        $etat=0;
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from SanteSpecialisteBundle:MedecinSpecialiste s 
    WHERE s.nom LIKE :nom AND s.prenom LIKE :prenom  AND s.etatverif LIKE :etat AND s.specialite LIKE :specialite AND s.cin LIKE :cin 
      ")
            ->setParameter('nom', '%' . $nom . '%')->setParameter('prenom', '%' . $prenom . '%')->setParameter('etat', '%' . $etat . '%')->setParameter('cin', '%' . $cin . '%')->setParameter('specialite', '%' . $specialite . '%');
        return $query->getResult();
    }

    function medecinOrdonnéverif()
    {
        $etat=0
        ;
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from SanteSpecialisteBundle:MedecinSpecialiste s 
    WHERE s.etatverif LIKE :etat
      ")->setParameter('etat', '%' . $etat . '%');
        return $query->getResult();
    }

    function medecinOrdonné($specialite)
    {
        $etat=1
        ;
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from SanteSpecialisteBundle:MedecinSpecialiste s 
    WHERE  s.specialite LIKE :specialite AND s.etatverif LIKE :etat ORDER BY s.rating DESC 
      ")->setParameter('specialite', '%' . $specialite . '%')->setParameter('etat', '%' . $etat . '%');
        return $query->getResult();
    }
    function nbmedecin($specialite)
    {
        $etat=1;
        $query = $this->getEntityManager()
            ->createQuery(" 
    select count(s) AS  nb from SanteSpecialisteBundle:MedecinSpecialiste s 
    WHERE  s.specialite LIKE :specialite AND s.etatverif LIKE :etat
      ")->setParameter('specialite', '%' . $specialite . '%')->setParameter('etat', '%' . $etat . '%');
        return $query->getResult();
    }
}
