<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * nformationContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nformationContactRepository extends \Doctrine\ORM\EntityRepository
{
}
