<?php

namespace BoutiqueBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findhistogramme($idf)
    {
        $query=$this->getEntityManager()->createQuery(
            "select c.nom ,COUNT (c.nom) as nbnom from BoutiqueBundle:Commande c
              WHERE  c.idf = :idf
             Group BY c.nom ORDER BY nbnom ASC "
        )
        ->setParameter('idf',$idf);
        return $query->getResult();
    }


}
//select c.nom COUNT c.nom from BoutiqueBundle:Commande c
//GROUP (c.nom) ORDER c.nom DESC