<?php

namespace Enseignant\EnseignantBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{

    public function avgrating()
    {
        $query=$this->getEntityManager()->createQuery(
            "select c.idB , AVG(c.rating)  from EnseignantEnseignantBundle:Rating c
             Group BY c.idB  "
        );
        return $query->getResult();
    }

}
