<?php

namespace Loisirs\LoisirsBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * BonplanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonplanRepository extends EntityRepository
{
    public function findBonplan($p){
        $query=$this->getEntityManager()->createQuery(
            "select m from LoisirsLoisirsBundle:Bonplan m WHERE m.region like :p  "
        )->setParameter('p','%'.$p.'%');
        return $query->getResult();
    }
    public function findOrdreBonplan(){
        $query=$this->getEntityManager()->createQuery(
            "select m from LoisirsLoisirsBundle:Bonplan m ORDER BY m.rating DESC "
        );
        return $query->getResult();
    }
    public function findBonplanNom($p){
        $query=$this->getEntityManager()->createQuery(
            "select m from LoisirsLoisirsBundle:Bonplan m WHERE m.nom like :p ORDER BY m.rating DESC "
        )->setParameter('p','%'.$p.'%');
        return $query->getResult();
    }

}
