<?php

namespace Loisirs\LoisirsBundle\Repository;

/**
 * ConseilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConseilRepository extends \Doctrine\ORM\EntityRepository
{

    public function findConseilJour(){
        $query=$this->getEntityManager()->createQuery(
            "select m from LoisirsLoisirsBundle:Conseil m WHERE m.date = CURRENT_DATE()  "
        );
        return $query->getResult();
    }
}
