<?php

namespace Loisirs\LoisirsBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository
{

    public function findRecette($p){
        $query=$this->getEntityManager()->createQuery(
            "select m from LoisirsLoisirsBundle:Recette m WHERE m.nom LIKE :p"
        )->setParameter('p','%'.$p.'%');
        return $query->getResult();
    }
}
