<?php

namespace bsitterBundle\Repository;

/**
 * BabySitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabySitterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBs($p){
        $em = $this->getEntityManager();

        $queryText  = "SELECT s FROM UserBundle:User s ";
        $queryText .= "WHERE :edition like s.roles";

        $query = $em->createQuery($queryText);
        $query->setParameter('edition', $p);

        return $query->getResult();
    }
    public function findId($p){
        $em = $this->getEntityManager();

        $queryText  = "SELECT s FROM UserBundle:User s ";
        $queryText .= "WHERE :edition like s.id";

        $query = $em->createQuery($queryText);
        $query->setParameter('edition', $p);

        return $query->getResult();
    }
    public function findVille($p){
        $em = $this->getEntityManager();

        $queryText  = "SELECT s FROM UserBundle:User s ";
        $queryText .= "WHERE :edition like s.ville";

        $query = $em->createQuery($queryText);
        $query->setParameter('edition', $p);

        return $query->getResult();
    }
}
