<?php

namespace bsitterBundle\Repository;

/**
 * BabySitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBesoin($p){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT s FROM bsitterBundle:besoin s WHERE s.idp like :e");
        $query->setParameter('e', $p);
        return $query->getResult();
    }

}