<?php

namespace Sante\articleBundle\Repository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends \Doctrine\ORM\EntityRepository
{
    function UpdateEtat($etat,$idarticle)
    {

           $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('SantearticleBundle:article', 'p')
            ->set('p.etat','?1')
            ->where('p.idarticle = ?2')
            ->setParameter(1,$etat)
            ->setParameter(2,$idarticle)
            ;
        $q=$qB->getQuery();
        $q->execute() ;
    }
    function liker($nbjaime,$idarticle)
    {

        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('SantearticleBundle:article', 'p')
            ->set('p.nblike','?1')
            ->where('p.idarticle = ?2')
            ->setParameter(1,$nbjaime)
            ->setParameter(2,$idarticle)
        ;
        $q=$qB->getQuery();
        $q->execute() ;
    }

    function findarticle($mot,$etat)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from SantearticleBundle:article s 
    WHERE s.body LIKE :mot AND s.etat LIKE :etat
    ORDER BY s.datepublication DESC 
      ")
            ->setParameter('mot', '%' . $mot . '%')->setParameter('etat', '%' . $etat . '%');
        return $query->getResult();
    }
    function findarticlepersonnel($mot,$etat)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from SantearticleBundle:article s 
    WHERE s.body LIKE :mot AND s.idauteur LIKE :etat
    ORDER BY s.datepublication DESC 
      ")
            ->setParameter('mot', '%' . $mot . '%')->setParameter('etat', '%' . $etat . '%');
        return $query->getResult();
    }
    function articletrié($etat)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from SantearticleBundle:article s 
    WHERE s.etat LIKE :etat
    ORDER BY s.datepublication DESC 
      ")->setParameter('etat', '%' . $etat . '%');
        return $query->getResult();
    }
    function articletriépersonnel($etat)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from SantearticleBundle:article s 
    WHERE s.idauteur LIKE :etat
    ORDER BY s.datepublication DESC 
      ")->setParameter('etat', '%' . $etat . '%');
        return $query->getResult();
    }
    function CalcularticleTotal($etat)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select count(s) as nb from SantearticleBundle:article s 
    WHERE s.idauteur LIKE :etat
      ")->setParameter('etat', '%' . $etat . '%');
        return $query->getResult();
    }
    function Calcularticleaccepté($id,$etat)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select count(s) as nb from SantearticleBundle:article s 
    WHERE s.idauteur LIKE :id AND  s.etat like :etat
      ")->setParameter('etat', '%' . $etat . '%')->setParameter('id', '%' . $id . '%');
        return $query->getResult();
    }

    function findBestarticle($etat)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select s from SantearticleBundle:article s 
    WHERE s.etat LIKE :etat
    ORDER BY s.nblike DESC 
      ")->setParameter('etat', '%' . $etat . '%');
        return $query->getResult();
    }

}
