<?php

namespace Sante\articleBundle\Repository;

/**
 * likearticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class likearticleRepository extends \Doctrine\ORM\EntityRepository
{
    function UpdateEtat($etat,$idarticle,$idliker)
    {

        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('SantearticleBundle:likearticle', 'p')
            ->set('p.likeetat','?1')
            ->where('p.idarticle = ?2 and p.idliker = ?3')
            ->setParameter(1,$etat)
            ->setParameter(2,$idarticle)
            ->setParameter(3,$idliker)
        ;
        $q=$qB->getQuery();
        $q->execute() ;
    }
}
