<?php

namespace Sante\articleBundle\Repository;

/**
 * notifarticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notifarticleRepository extends \Doctrine\ORM\EntityRepository
{

    function Updatenotif($idmedecin)
    {

        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('SantearticleBundle:notifarticle', 'p')
            ->set('p.etatnotif','?1')
            ->where('p.idmedecin = ?2 and p.etatnotif = ?3')
            ->setParameter(1,1)
            ->setParameter(2,$idmedecin)
            ->setParameter(3,0)
        ;
        $q=$qB->getQuery();
        $q->execute() ;
    }
}
