<?php

namespace JardinDenfant\ProfilJDBundle\Repository;

/**
 * adresseJardinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adresseJardinRepository extends \Doctrine\ORM\EntityRepository
{
}
