<?php

namespace JardinDenfant\ProfilJDBundle\Repository;

/**
 * horaireTravailJardinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class horaireTravailJardinRepository extends \Doctrine\ORM\EntityRepository
{
}
