<?php

namespace JardinDenfant\ProfilJDBundle\Repository;

/**
 * ProfilJDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilJDRepository extends \Doctrine\ORM\EntityRepository
{




    function findadresse($p)
    {
        $query=$this->getEntityManager()->createQuery(
            "select m from JardinDenfantProfilJDBundle:ProfilJD m where m.adresse like :p")->setParameter('p','%'.$p.'%');
        return $query->getResult();

    }


    function  findvalide()
    {
        $query=$this->getEntityManager()->createQuery(
            "select m from JardinDenfantProfilJDBundle:ProfilJD m where m.valide =1 ORDER BY m.rating DESC ");
        return $query->getResult();
    }

    public function  topJardin()
    {
        $query=$this->getEntityManager()->createQuery(
            "select m from JardinDenfantProfilJDBundle:ProfilJD m where m.valide =1  ORDER BY m.rating DESC ");
        return $query->getResult();
    }
        public function nbreJardin()
        {

            $query = $this->getEntityManager()
                ->createQuery(" 
    select count(j) AS  nb from JardinDenfantProfilJDBundle:ProfilJD j")

            ;
            return $query->getResult();

        }







}
