<?php

namespace JardinDenfant\ProfilJDBundle\Repository;

/**
 * UserEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEventsRepository extends \Doctrine\ORM\EntityRepository
{
    function getNb($e)
    {

        return $this->createQueryBuilder('l')

            ->select('COUNT(l)')
            ->where("l.evenement=:e")
            ->setParameter('e',$e)
            ->getQuery()

            ->getSingleScalarResult();



    }


    public function  findevents($id,$ide)
    {
        $query =$this->getEntityManager()->createQuery("delete JardinDenfantProfilJDBundle:UserEvents ue 
 where ue.user=:id and ue.evenement=:ide
")->setParameter('id',$id)->setParameter('ide',$ide);
        return $query->execute();



    }

    public function  findUsersEvents($id,$ide)
    {
        $query =$this->getEntityManager()->createQuery("
select ue from JardinDenfantProfilJDBundle:UserEvents ue where  ue.user=:id and  ue.evenement=:ide")
            ->setParameter('id',$id)->setParameter('ide',$ide)
            ->setMaxResults(1)
        ;
            //->setParameter('ide',$ide)
        ;
        return $query->execute();
    }
public function findevn($id)
{
$query =$this->getEntityManager()->createQuery("
select ue from JardinDenfantProfilJDBundle:UserEvents ue where  ue.user=:id ")
->setParameter('id',$id);
    //->setParameter('ide',$ide)
;
return $query->execute();
}
}
